version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "3206:5000"
    volumes:
      - ../deploy:/app/../deploy:ro
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=fintrack_user
      - MYSQL_PASSWORD=fintrack_pass
      - MYSQL_DATABASE=fintrack_db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=fintrack_db
      - MYSQL_USER=fintrack_user
      - MYSQL_PASSWORD=fintrack_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data: 